report MemberID on registerMember
kmarroq1/RentMe-App pull request #51
Opened 2022-04-11 16:17 UTC by sd00070

* create `RegisterMember` stored procedure
* attach stored procedure to DAL
* pass insert ID from DAL to controller to view
* display MemberID in MessageBox

2022-04-11 20:28 UTC, sd00070 commented
Once this branch is pulled, you all will need to run the RegisterMember.sql script to add the stored procedure to your db.

2022-04-12 15:51 UTC, kmarroq1 requested changes
Everything looks good! Just clean up the dal, then should be good to be merged!

2022-04-12 15:51 UTC, kmarroq1 commented on RentMe-App/DAL/MemberDBDAL.cs
>          /// </summary>
Clean this file.

2022-04-13 04:31 UTC, sd00070 commented
merge should be ready

2022-04-13 18:18 UTC, kmarroq1 approved these changes

2022-04-13 18:18 UTC, merged